CREATE TABLE USERS (
  ID  SERIAL NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  ADMIN_CODE INTEGER DEFAULT 0,
  ADDRESS VARCHAR(255) DEFAULT NULL,
  PHONE VARCHAR(50) DEFAULT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

INSERT INTO USERS (NAME, EMAIL, PASSWORD, ADMIN_CODE, ADDRESS, PHONE) VALUES
('admin', 'admin@example.com','$2a$08$CekzJRYhb5bzp5mx/eZmX.grG92fRXo267QVVyRs0IE.V.zeCIw8S', 1, '東京都品川区1-1', '09012345678'),
('guest', 'guest@example.com','test1234', 9, '東京都荒川区1-1', '09012345678'),
('test1', 'test1@example.com','test1234', 0, '東京都荒川区1-1', '09012345678'),
('test2', 'test2@example.com','test1234', 0, '東京都渋谷区1-1', '09012345678');






CREATE TABLE WORKS (
  ID  SERIAL NOT NULL,
  USER_ID integer default 0,
  CONTENT VARCHAR(255) NOT NULL,
  START_AT timestamp NOT NULL,
  END_AT timestamp NOT NULL,
  CREATED_AT timestamp default CURRENT_TIMESTAMP,
  UPDATED_AT timestamp default CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

INSERT INTO WORKS (USER_ID, CONTENT, START_AT, END_AT) VALUES
(2, 'ゲスト用Ａ会社の打刻', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'ゲスト用Ａ会社の打刻', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'ゲスト用Ｂ会社の打刻', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'ゲスト用Ｂ会社の打刻', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'ゲスト用Ｃ会社の打刻', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

