CREATE TABLE USERS (
  ID SERIAL NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  ADMIN_CODE INTEGER DEFAULT 0,
  GENDER INTEGER DEFAULT 0,
  ADDRESS VARCHAR(255) DEFAULT NULL,
  PHONE VARCHAR(50) DEFAULT NULL,
  BIRTHDAY DATE,
  AGE VARCHAR(3),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);

INSERT INTO USERS (NAME, EMAIL, PASSWORD, ADMIN_CODE, ADDRESS, PHONE) VALUES
('admin', 'admin@example.com','$2a$08$CekzJRYhb5bzp5mx/eZmX.grG92fRXo267QVVyRs0IE.V.zeCIw8S', 1, '東京都品川区1-1', '09012345678'),
('guest', 'guest@example.com','test1234', 9, '東京都荒川区1-1', '09012345678'),
('test1', 'test1@example.com','test1234', 0, '東京都荒川区1-1', '09012345678'),
('test2', 'test2@example.com','test1234', 0, '東京都渋谷区1-1', '09012345678');





CREATE TABLE WORKS (
  ID SERIAL NOT NULL,
  USER_ID INTEGER NOT NULL DEFAULT 0,
  CONTENT VARCHAR(255) NOT NULL,
  START_AT TIMESTAMP NOT NULL,
  END_AT TIMESTAMP,
  WORKTIME numeric DEFAULT 0,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);

INSERT INTO WORKS (USER_ID, CONTENT, START_AT, END_AT, WORKTIME) VALUES
(2, 'ゲスト用Ａ会社', '2022-02-01 08:30:00', '2022-02-01 17:30:00', 8.0),
(2, 'ゲスト用Ａ会社', '2022-02-02 08:30:00', '2022-02-02 17:30:00', 8.0),
(2, 'ゲスト用Ｂ会社', '2022-02-03 08:30:00', '2022-02-03 17:30:00', 8.0),
(2, 'ゲスト用Ｂ会社', '2022-02-04 08:30:00', '2022-02-04 17:30:00', 8.0),
(2, 'ゲスト用Ｃ会社', '2022-02-05 08:30:00', '2022-02-05 17:30:00', 8.0);





CREATE TABLE QBOARDS (
  ID SERIAL NOT NULL,
  HEAD_ID INTEGER NOT NULL DEFAULT 0,
  BODY_ID INTEGER NOT NULL DEFAULT 1,
  USER_ID INTEGER NOT NULL DEFAULT 0,
  STATUS_CODE INTEGER DEFAULT 1,
  NAME VARCHAR(100) NOT NULL,
  CONTENT VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);

INSERT INTO QBOARDS (HEAD_ID, BODY_ID, USER_ID, NAME, CONTENT) VALUES
(1, 1, 1, '管理者', '荒らし行為は見つけ次第、管理者が削除します。');




--◆以下、Web会議室用のテーブル。
CREATE TABLE TOPICS
(
    TOPICNO         VARCHAR(12) NOT NULL,
    SUBJECT         VARCHAR(128) DEFAULT NULL,
	USER_ID			INTEGER NOT NULL DEFAULT 0,
    CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (TOPICNO)
);


CREATE TABLE POSTS
(
    TOPICNO         VARCHAR(12) NOT NULL,
    POSTNO          INTEGER NOT NULL DEFAULT 0,
    POST            VARCHAR(1280) DEFAULT NULL,
	USER_ID			INTEGER NOT NULL DEFAULT 0,
    CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (TOPICNO, POSTNO)
);


CREATE TABLE POST_RATINGS
(
    TOPICNO         VARCHAR(12) NOT NULL,
    POSTNO          INTEGER NOT NULL DEFAULT 0,
	USER_ID			INTEGER NOT NULL DEFAULT 0,
    RATEDBY         VARCHAR(8) NOT NULL,
    RATING_FLG      INTEGER NOT NULL DEFAULT 0,
    RATED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(TOPICNO, POSTNO, USER_ID)
);



-- 採番マスタ
CREATE TABLE NUMBERING_LEDGER (
  -- 番号体系コード
  NUMBERING_CD varchar(3) NOT NULL,
  -- 有効年度
  AVAIL_YEAR varchar(4) NOT NULL,
  -- 次番号
  NEXTNO decimal(9,0) DEFAULT NULL,
  -- 桁数
--  DIGITS decimal(9,0) DEFAULT NULL,
  UPD_USER_ID INTEGER NOT NULL DEFAULT 0,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (NUMBERING_CD, AVAIL_YEAR)
);

-- 採番マスタの初期番号（※このデータがないと、一番最初の新規登録でエラーが発生します。）
INSERT INTO NUMBERING_LEDGER (NUMBERING_CD, AVAIL_YEAR, NEXTNO) VALUES
('T00', '2022', 1);



--◆Web会議室データを初期化したい場合。
-- 採番マスタを初期番号に戻す。
--UPDATE NUMBERING_LEDGER SET NEXTNO = 1 WHERE NUMBERING_CD = 'T00' AND AVAIL_YEAR = '2022';
UPDATE NUMBERING_LEDGER SET NEXTNO = 1 WHERE NUMBERING_CD = 'T00';
--'2023年版'の採番用データを作りたい場合。
--INSERT INTO NUMBERING_LEDGER (NUMBERING_CD, AVAIL_YEAR, NEXTNO) VALUES ('T00', '2023', 1);
DELETE FROM TOPICS;
DELETE FROM POSTS;
DELETE FROM POST_RATINGS;

